pygments: true
permalink: /posts/:title
auto: true
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]

name: derivatived
phonetic: derivative&#183;d
url: http://blog.derivatived.com
description: Building autonomous warehouse vehicles.
twitter: derivatived
github: derivatived/self-driving-car
gravatar_url: http://gravatar.com/avatar/6f63cde8b16b035280ca615f621a6c8c
