markdown: rdiscount
pygments: true
permalink: /posts/:title
auto: true
rdiscount:
  extensions: [smart]

name: derivative&#183;d
url: http://blog.derivatived.com
description: Making data user friendly.
twitter: derivatived
github: derivatived
gravatar_url: http://gravatar.com/avatar/6f63cde8b16b035280ca615f621a6c8c
