markdown: rdiscount
pygments: true
permalink: /posts/:title
auto: true
rdiscount:
  extensions: [smart]

name: derivative&middot;d
url: http://derivatived.com
description: A fantastic blog that is fantastic.
twitter: DerivativeD
github: derivatived
gravatar_url: http://gravatar.com/avatar/6f63cde8b16b035280ca615f621a6c8c
